CREATE TABLE "podsearch_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "podsearch_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "podsearch_playlist" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "podsearch_playlist_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"youtubeId" varchar(255) NOT NULL,
	"title" varchar(500) NOT NULL,
	"description" text,
	"channelName" varchar(255),
	"channelId" varchar(255),
	"url" varchar(500) NOT NULL,
	"totalVideos" integer DEFAULT 0,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"lastSyncAt" timestamp with time zone,
	CONSTRAINT "podsearch_playlist_youtubeId_unique" UNIQUE("youtubeId")
);
--> statement-breakpoint
CREATE TABLE "podsearch_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "podsearch_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "podsearch_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "podsearch_transcript" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "podsearch_transcript_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"videoId" integer NOT NULL,
	"youtubeId" varchar(255) NOT NULL,
	"fullText" text NOT NULL,
	"language" varchar(10) DEFAULT 'en',
	"duration" real,
	"segmentsCount" integer DEFAULT 0,
	"whisperModel" varchar(50),
	"segments" jsonb,
	"processingMetadata" jsonb,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "podsearch_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "podsearch_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "podsearch_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
CREATE TABLE "podsearch_video" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "podsearch_video_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"youtubeId" varchar(255) NOT NULL,
	"playlistId" integer,
	"title" varchar(500) NOT NULL,
	"description" text,
	"duration" integer,
	"publishedAt" timestamp with time zone,
	"thumbnailUrl" varchar(500),
	"url" varchar(500) NOT NULL,
	"localFilePath" varchar(1000),
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"processingStartedAt" timestamp with time zone,
	"processingCompletedAt" timestamp with time zone,
	"errorMessage" text,
	"retryCount" integer DEFAULT 0,
	"hasTranscript" boolean DEFAULT false,
	"transcriptProcessedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "podsearch_video_youtubeId_unique" UNIQUE("youtubeId")
);
--> statement-breakpoint
ALTER TABLE "podsearch_account" ADD CONSTRAINT "podsearch_account_userId_podsearch_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."podsearch_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "podsearch_post" ADD CONSTRAINT "podsearch_post_createdById_podsearch_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."podsearch_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "podsearch_session" ADD CONSTRAINT "podsearch_session_userId_podsearch_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."podsearch_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "podsearch_transcript" ADD CONSTRAINT "podsearch_transcript_videoId_podsearch_video_id_fk" FOREIGN KEY ("videoId") REFERENCES "public"."podsearch_video"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "podsearch_video" ADD CONSTRAINT "podsearch_video_playlistId_podsearch_playlist_id_fk" FOREIGN KEY ("playlistId") REFERENCES "public"."podsearch_playlist"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "podsearch_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "playlist_youtube_id_idx" ON "podsearch_playlist" USING btree ("youtubeId");--> statement-breakpoint
CREATE INDEX "playlist_channel_id_idx" ON "podsearch_playlist" USING btree ("channelId");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "podsearch_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "podsearch_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "podsearch_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "transcript_video_id_idx" ON "podsearch_transcript" USING btree ("videoId");--> statement-breakpoint
CREATE INDEX "transcript_youtube_id_idx" ON "podsearch_transcript" USING btree ("youtubeId");--> statement-breakpoint
CREATE INDEX "transcript_language_idx" ON "podsearch_transcript" USING btree ("language");--> statement-breakpoint
CREATE INDEX "video_youtube_id_idx" ON "podsearch_video" USING btree ("youtubeId");--> statement-breakpoint
CREATE INDEX "video_playlist_id_idx" ON "podsearch_video" USING btree ("playlistId");--> statement-breakpoint
CREATE INDEX "video_status_idx" ON "podsearch_video" USING btree ("status");--> statement-breakpoint
CREATE INDEX "video_published_at_idx" ON "podsearch_video" USING btree ("publishedAt");--> statement-breakpoint
CREATE INDEX "video_has_transcript_idx" ON "podsearch_video" USING btree ("hasTranscript");