CREATE TABLE "podsearch_search_execution" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "podsearch_search_execution_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255),
	"query" varchar(500) NOT NULL,
	"videoId" integer,
	"topK" integer DEFAULT 5,
	"inputClipsCount" integer DEFAULT 0,
	"outputSegmentsCount" integer DEFAULT 0,
	"inputClipsMetadata" jsonb,
	"outputSegmentsMetadata" jsonb,
	"processingTimeMs" integer,
	"status" varchar(20) DEFAULT 'success',
	"errorMessage" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "podsearch_transcript" DROP CONSTRAINT "podsearch_transcript_videoId_podsearch_video_id_fk";
--> statement-breakpoint
DROP INDEX "transcript_video_id_idx";--> statement-breakpoint
DROP INDEX "transcript_youtube_id_idx";--> statement-breakpoint
DROP INDEX "video_has_transcript_idx";--> statement-breakpoint
ALTER TABLE "podsearch_video" ADD COLUMN "transcriptId" integer;--> statement-breakpoint
ALTER TABLE "podsearch_search_execution" ADD CONSTRAINT "podsearch_search_execution_userId_podsearch_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."podsearch_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "podsearch_search_execution" ADD CONSTRAINT "podsearch_search_execution_videoId_podsearch_video_id_fk" FOREIGN KEY ("videoId") REFERENCES "public"."podsearch_video"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "search_execution_video_id_idx" ON "podsearch_search_execution" USING btree ("videoId");--> statement-breakpoint
CREATE INDEX "search_execution_created_at_idx" ON "podsearch_search_execution" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "search_execution_status_idx" ON "podsearch_search_execution" USING btree ("status");--> statement-breakpoint
ALTER TABLE "podsearch_video" ADD CONSTRAINT "podsearch_video_transcriptId_podsearch_transcript_id_fk" FOREIGN KEY ("transcriptId") REFERENCES "public"."podsearch_transcript"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "video_transcript_id_idx" ON "podsearch_video" USING btree ("transcriptId");--> statement-breakpoint
ALTER TABLE "podsearch_transcript" DROP COLUMN "videoId";--> statement-breakpoint
ALTER TABLE "podsearch_transcript" DROP COLUMN "youtubeId";--> statement-breakpoint
ALTER TABLE "podsearch_transcript" DROP COLUMN "fullText";--> statement-breakpoint
ALTER TABLE "podsearch_transcript" DROP COLUMN "duration";--> statement-breakpoint
ALTER TABLE "podsearch_transcript" DROP COLUMN "segmentsCount";--> statement-breakpoint
ALTER TABLE "podsearch_transcript" DROP COLUMN "whisperModel";--> statement-breakpoint
ALTER TABLE "podsearch_video" DROP COLUMN "hasTranscript";--> statement-breakpoint
ALTER TABLE "podsearch_video" DROP COLUMN "transcriptProcessedAt";