CREATE TABLE "podsearch_transcript_request" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "podsearch_transcript_request_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"youtubeId" varchar(255) NOT NULL,
	"timestamp" integer NOT NULL,
	"duration" integer NOT NULL,
	"transcriptText" text,
	"success" boolean DEFAULT true,
	"errorMessage" text,
	"processingTimeMs" integer,
	"userAgent" varchar(500),
	"ipAddress" varchar(45),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE INDEX "transcript_request_youtube_id_idx" ON "podsearch_transcript_request" USING btree ("youtubeId");--> statement-breakpoint
CREATE INDEX "transcript_request_created_at_idx" ON "podsearch_transcript_request" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "transcript_request_success_idx" ON "podsearch_transcript_request" USING btree ("success");