CREATE TABLE "podsearch_chapter_similarity" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "podsearch_chapter_similarity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sourceChapterId" integer NOT NULL,
	"destChapterId" integer NOT NULL,
	"similarityScore" real NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "podsearch_chapter" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "podsearch_chapter_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"videoId" integer NOT NULL,
	"chapterIdx" integer NOT NULL,
	"chapterName" varchar(500) NOT NULL,
	"chapterSummary" text NOT NULL,
	"startTime" integer NOT NULL,
	"endTime" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "podsearch_chapter_similarity" ADD CONSTRAINT "podsearch_chapter_similarity_sourceChapterId_podsearch_chapter_id_fk" FOREIGN KEY ("sourceChapterId") REFERENCES "public"."podsearch_chapter"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "podsearch_chapter_similarity" ADD CONSTRAINT "podsearch_chapter_similarity_destChapterId_podsearch_chapter_id_fk" FOREIGN KEY ("destChapterId") REFERENCES "public"."podsearch_chapter"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "podsearch_chapter" ADD CONSTRAINT "podsearch_chapter_videoId_podsearch_video_id_fk" FOREIGN KEY ("videoId") REFERENCES "public"."podsearch_video"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "chapter_similarity_source_idx" ON "podsearch_chapter_similarity" USING btree ("sourceChapterId");--> statement-breakpoint
CREATE INDEX "chapter_similarity_dest_idx" ON "podsearch_chapter_similarity" USING btree ("destChapterId");--> statement-breakpoint
CREATE INDEX "chapter_similarity_score_idx" ON "podsearch_chapter_similarity" USING btree ("similarityScore");--> statement-breakpoint
CREATE INDEX "chapter_video_id_idx" ON "podsearch_chapter" USING btree ("videoId");--> statement-breakpoint
CREATE INDEX "chapter_video_idx_idx" ON "podsearch_chapter" USING btree ("videoId","chapterIdx");--> statement-breakpoint
ALTER TABLE "podsearch_transcript_request" DROP COLUMN "userAgent";--> statement-breakpoint
ALTER TABLE "podsearch_transcript_request" DROP COLUMN "ipAddress";